In [20]:
%matplotlib inline
import pandas as pd
import os,sys
import numpy as np
import math 
import matplotlib.pyplot as plt

np.set_printoptions(precision=8, suppress=True)

In [21]:
fl = open(r"KhAB/n1.txt", "r")
u1 = np.zeros((101, 4))
i = 0
for line in fl:
    tmp = line.split(" ")
    u1[i][0] = float(tmp[0])
    u1[i][1] = float(tmp[1])
    u1[i][2] = float(tmp[2])
    u1[i][3] = float(tmp[3])
    i += 1
fl.close()
print(u1)

[[783124.67777702    738.00361949   1431.0308192       1.90677753]
 [275411.93406048   1140.67334708   1127.25988124      0.85227037]
 [178303.03942847   1250.55014623   1021.51317939      0.60892369]
 [135536.6771661    1309.80048422    960.45107351      0.49231295]
 [113529.27318244   1344.50713944    923.36912581      0.42894042]
 [101667.19431888   1364.6302594     901.42425196      0.39347568]
 [ 94946.48915652   1376.34579174    888.49783893      0.37281169]
 [ 91757.48560555   1381.61249572    882.65074917      0.3626768 ]
 [ 91128.04976531   1381.89090091    882.34104228      0.36031535]
 [ 91154.99174138   1381.07470254    883.24500947      0.360053  ]
 [ 91162.46636856   1381.02323844    883.284519        0.36006642]
 [ 91169.79354587   1380.9727918     883.32324533      0.36007957]
 [ 91176.98924263   1380.92325254    883.36127307      0.36009249]
 [ 91184.06651994   1380.87453062    883.39867145      0.36010519]
 [ 91191.03624266   1380.82655116    883.43549804      0.36011

In [22]:
fl = open(r"Bakh/n2.txt", "r")
u2 = np.zeros((101, 4))
i = 0
for line in fl:
    tmp = line.split(" ")
    u2[i][0] = float(tmp[0])
    u2[i][1] = float(tmp[1])
    u2[i][2] = float(tmp[2])
    u2[i][3] = float(tmp[3])
    i += 1
fl.close()
print(u2)

[[783124.67777702    738.00361949   1431.0308192       1.90677753]
 [275411.89060525   1140.67344004   1127.25979596      0.8522703 ]
 [178302.99774336   1250.55027683   1021.51304797      0.60892362]
 [135536.63664053   1309.80064449    960.45090456      0.49231289]
 [113529.23236584   1344.50732672    923.36892314      0.42894036]
 [101667.15180617   1364.6304733     901.424017        0.39347562]
 [ 94946.44399846   1376.34603235    888.49757236      0.37281163]
 [ 91757.43666129   1381.61276421    882.65045057      0.36267673]
 [ 91127.99576851   1381.89119912    882.34071054      0.36031527]
 [ 91159.33335202   1380.89410004    883.17157114      0.36010009]
 [ 91185.11969948   1380.00516371    882.85270182      0.36033205]
 [ 91210.45582612   1379.13394122    882.54049014      0.36055968]
 [ 91235.3937175    1378.27852373    882.23423465      0.36078346]
 [ 91259.97579573   1377.43734974    881.93336098      0.36100378]
 [ 91284.23727142   1376.60912004    881.63739081      0.36122

In [23]:
d = abs(u1 - u2)/u1*100
dl = np.zeros(len(u1))
for i in range(len(dl)):
    dl[i] = max(d[i])
print(max(dl))    
print(d)    

44.48892974190316
[[ 0.          0.          0.          0.        ]
 [ 0.00001578  0.00000815  0.00000757  0.00000819]
 [ 0.00002338  0.00001044  0.00001287  0.00001049]
 [ 0.0000299   0.00001224  0.00001759  0.00001228]
 [ 0.00003595  0.00001393  0.00002195  0.00001397]
 [ 0.00004182  0.00001567  0.00002607  0.00001572]
 [ 0.00004756  0.00001748  0.00003     0.00001753]
 [ 0.00005334  0.00001943  0.00003383  0.00001948]
 [ 0.00005925  0.00002158  0.0000376   0.00002163]
 [ 0.00476289  0.01307695  0.0083146   0.0130786 ]
 [ 0.02484941  0.07371887  0.04888766  0.07377311]
 [ 0.04460061  0.13315618  0.08861481  0.13333349]
 [ 0.06405616  0.19151888  0.12758522  0.19188608]
 [ 0.0832484   0.24891334  0.16587194  0.24953409]
 [ 0.10220416  0.30542801  0.20353577  0.30636329]
 [ 0.12094599  0.36113758  0.24062809  0.36244599]
 [ 0.13949312  0.41610583  0.27719284  0.41784392]
 [ 0.15786209  0.47038784  0.31326798  0.47261029]
 [ 0.17606726  0.52403159  0.34888661  0.52679142]
 [ 0.19412123